twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates/'

    paths:
        # twig will look for the template first on this directory
        'instances/%env(INSTANCE)%/templates/': ~

when@test:
    twig:
        strict_variables: true
