services:
  iahx_opac:
    container_name: iahx-opac
    restart: unless-stopped
    build:
      context: .
      args:
        PHP_PM_MAX_CHILDREN: ${PHP_PM_MAX_CHILDREN}
        PHP_PM_START_SERVERS: ${PHP_PM_START_SERVERS}
        PHP_PM_MIN_SPARE_SERVERS: ${PHP_PM_MIN_SPARE_SERVERS}
        PHP_PM_MAX_SPARE_SERVERS: ${PHP_PM_MAX_SPARE_SERVERS}
        PHP_PM_MAX_REQUESTS: ${PHP_PM_MAX_REQUESTS}
        PHP_PM_PROCESS_IDLE_TIMEOUT: ${PHP_PM_PROCESS_IDLE_TIMEOUT}
        PHP_REQUEST_TERMINATE_TIMEOUT: ${PHP_REQUEST_TERMINATE_TIMEOUT}
    image: ${IMAGE_TAG}
    volumes:
      - static_files:/app/public
      - ./instances/:/app/instances
      - phpsock:/var/run
    environment:
      - TZ=${TIMEZONE}

  iahx_webserver:
    image: nginx:1.25-alpine
    container_name: iahx-webserver
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - static_files:/app/public
      - ./instances/:/app/instances
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./docker/nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./docker/nginx/robots.txt:/app/public/robots.txt
      - phpsock:/var/run
    depends_on:
      - iahx_opac
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - USE_AUTHENTICATION=${USE_AUTHENTICATION}
      - TZ=${TIMEZONE}
    networks:
      - nginx-proxy

  iahx_cache:
    image: bitnamilegacy/redis:7.2
    container_name: iahx-cache
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_AOF_ENABLED=no
      - TZ=${TIMEZONE}
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory ${APP_CACHE_MEMORY} --maxmemory-policy allkeys-lru

volumes:
  static_files:
  phpsock:

networks:
  nginx-proxy:
    external: true
