services:
  iahx_opac:
    container_name: iahx-opac
    restart: unless-stopped
    build:
      context: .
    image: ${IMAGE_TAG}
    volumes:
      - static_files:/app/public
      - ./instances/:/app/instances
      - phpsock:/var/run

  iahx_webserver:
    image: nginx:1.25-alpine
    container_name: iahx-webserver
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - static_files:/app/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - phpsock:/var/run
    depends_on:
      - iahx_opac
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
    networks:
      - nginx-proxy

volumes:
  static_files:
  phpsock:

networks:
  nginx-proxy:
      external: true
