FROM docker.io/bitnami/php-fpm:8.2 as builder

# Install build packages and git
RUN install_packages git autoconf build-essential

# Install PHP exstensions
ENV EXTENSION_DIR="/opt/bitnami/php/lib/php/extensions"
RUN pecl channel-update pecl.php.net
RUN pecl config-set ext_dir $EXTENSION_DIR \
       && pear config-set ext_dir $EXTENSION_DIR

RUN pecl install redis

FROM docker.io/bitnami/php-fpm:8.2

# Copy configuration
COPY ./docker/php/php-fpm.conf /opt/bitnami/php/etc/php-fpm.conf
COPY ./docker/php/custom.ini /opt/bitnami/php/etc/conf.d/custom.ini

# Copy extensions from builder
COPY --from=builder \
    /opt/bitnami/php/lib/php/extensions/redis.so \
    /opt/bitnami/php/lib/php/extensions/

ENV PHP_INI_SCAN_DIR /opt/bitnami/php/lib/inc

WORKDIR /app

# Install Symfony CLI
RUN curl -sS https://get.symfony.com/cli/installer | bash
RUN mv /root/.symfony5/bin/symfony /usr/local/bin/symfony

EXPOSE 8000

CMD ["symfony", "server:start"]
